package com.beathive.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="billingForm" 
 */
public class BillingForm extends BaseForm implements java.io.Serializable {

    protected String email;
    protected String promoCode;
    protected String created;
    protected String cardType;
    protected String accountNumber;
    protected String expirationMonth;
    protected String expirationYear;
    protected String areacode;
    protected String phone;
    protected String phoneNumber;
    protected String street1;
    protected String street2;
    protected String city;
    protected String province;
    protected String country;
    protected String postalCode;
    protected String firstName;
    protected String lastName;
    protected String middleName;
    protected Long userId;

    /** Default empty constructor. */
    public BillingForm() {}

    public String getEmail()
    {
        return this.email;
    }
   /**
    * @struts.validator type="required"
    * @struts.validator type="email"
    */

    public void setEmail( String email )
    {
        this.email = email;
    }

    public String getCreated()
    {
        return this.created;
    }
   /**
    */

    public void setCreated( String created )
    {
        this.created = created;
    }

    public String getCardType()
    {
        return this.cardType;
    }
    
   /**
    * @struts.validator type="required"
    */
    public void setCardType( String type )
    {
        this.cardType = type;
    }

    public String getAccountNumber()
    {
        return this.accountNumber;
    }
    
   /**
    * @struts.validator type="required
    * @struts.validator type="creditCard"
    */
    public void setAccountNumber( String accountNumber )
    {
        this.accountNumber = accountNumber;
    }

    public String getExpirationMonth()
    {
        return this.expirationMonth;
    }
   /**
    * @struts.validator type="required"
    */

    public void setExpirationMonth( String expirationMonth )
    {
        this.expirationMonth = expirationMonth;
    }

    public String getExpirationYear()
    {
        return this.expirationYear;
    }
   /**
    * @struts.validator type="required"
    */

    public void setExpirationYear( String expirationYear )
    {
        this.expirationYear = expirationYear;
    }

    public String getAreacode()
    {
        return this.areacode;
    }
   /**
    * @struts.validator type="required"
    */

    public void setAreacode( String areacode )
    {
        this.areacode = areacode;
    }

    public String getPhone()
    {
        return this.phone;
    }
   /**
    * @struts.validator type="required"
    */

    public void setPhone( String phone )
    {
        this.phone = phone;
    }

    public String getPhoneNumber()
    {
        return this.phoneNumber;
    }
   /**
    */

    public void setPhoneNumber( String phoneNumber )
    {
        this.phoneNumber = phoneNumber;
    }

    public String getStreet1()
    {
        return this.street1;
    }
   /**
    * @struts.validator type="required"
    */

    public void setStreet1( String street1 )
    {
        this.street1 = street1;
    }

    public String getStreet2()
    {
        return this.street2;
    }
   /**
    */

    public void setStreet2( String street2 )
    {
        this.street2 = street2;
    }

    public String getCity()
    {
        return this.city;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCity( String city )
    {
        this.city = city;
    }

    public String getProvince()
    {
        return this.province;
    }
   /**
    */

    public void setProvince( String province )
    {
        this.province = province;
    }

    public String getCountry()
    {
        return this.country;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCountry( String country )
    {
        this.country = country;
    }

    public String getPostalCode()
    {
        return this.postalCode;
    }
   /**
    */

    public void setPostalCode( String postalCode )
    {
        this.postalCode = postalCode;
    }

    public String getFirstName()
    {
        return this.firstName;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFirstName( String firstName )
    {
        this.firstName = firstName;
    }

    public String getLastName()
    {
        return this.lastName;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLastName( String lastName )
    {
        this.lastName = lastName;
    }

    public String getMiddleName()
    {
        return this.middleName;
    }
   /**
    */

    public void setMiddleName( String middleName )
    {
        this.middleName = middleName;
    }

    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        this.accountNumber = "";
        this.expirationMonth = "";
        this.expirationYear = "";
    }

	/**
	 * @return the userId
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * @return the promoCode
	 */
	public String getPromoCode() {
		return promoCode;
	}

	/**
	 * @param promoCode the promoCode to set
	 */
	public void setPromoCode(String promoCode) {
		this.promoCode = promoCode;
	}

}
