package com.beathive.webapp.form;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.apache.commons.lang.StringUtils;
import org.apache.struts.action.ActionMapping;


/**
 * <b>Note:</b> xdoclet template modified to skip User fields in POJO
 *
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="loopSearchForm" 
 */
public class LoopFormSearch extends BaseForm implements java.io.Serializable {
	
    protected InstrumentForm instrument = new InstrumentForm();
    protected String instrumentId;
    protected String storeId;
    protected String modified;
    protected String statusId;
    protected PriceForm price = new PriceForm();
    protected String keyword;
    protected String score;
    protected String formatId;
    protected String genreId;
    protected String trackpackId;
    
    // used inversely to hide the ones already owned by this viewer
    protected boolean ownedByViewer;
    protected boolean aFavorite;
    
    protected String sort;
    protected String dir;
    protected String preffrm;
    protected String size="10";
    
    private String energy;
    private String feel;
    private String keynote;
    private String mood;
    private String origin;
    private String passage;
    private String scale;
    private String sonority;
    private String texture;
    private String timesignature;
    
    
    protected Map descriptors = new HashMap();
	private String bpm;
    
	public boolean isAFavorite() {
		return aFavorite;
	}

	public boolean getAFavorite() {
		return aFavorite;
	}
	
	public void setAFavorite(boolean favorite) {
		this.aFavorite = favorite;
	}
    
    /** Default empty constructor. */
    public LoopFormSearch() {}

    public InstrumentForm getInstrumentForm()
    {
        return this.instrument;
    }
   /**
    * @struts.validator
    */
    public void setInstrumentForm( InstrumentForm instrument )
    {
        this.instrument = instrument;
    }
    /** 
     *  Getter/Setter pair so BeanUtil.copyProperties(dest, orig) will work 
     *  Any properties modified in the web tier should use the get/setInstrumentForm 
     *  methods.
     */
    public com.beathive.model.Instrument getInstrument() throws Exception
    {
        return (com.beathive.model.Instrument) com.beathive.util.ConvertUtil.convert(this.instrument);
    }
    public void setInstrument(com.beathive.model.Instrument instrument) throws Exception
    {
        setInstrumentForm((InstrumentForm) com.beathive.util.ConvertUtil.convert(instrument));
    }
    public String getInstrumentId()
    {
        return this.instrumentId;
    }
   /**
    */
    public void setInstrumentId( String instrumentId )
    {
        this.instrumentId = instrumentId;
        if (StringUtils.isNumeric(instrumentId )){
        	instrument.setId(instrumentId);
        }
    }


    public String getModified()
    {
        return this.modified;
    }
   /**
    */
    public void setModified( String modified )
    {
        this.modified = modified;
    }

    public PriceForm getPriceForm()
    {
        return this.price;
    }

    public void setPriceForm( PriceForm price )
    {
        this.price = price;
    }
    /** 
     *  Getter/Setter pair so BeanUtil.copyProperties(dest, orig) will work 
     *  Any properties modified in the web tier should use the get/setPriceForm 
     *  methods.
     */
    public com.beathive.model.Price getPrice() throws Exception
    {
        return (com.beathive.model.Price) com.beathive.util.ConvertUtil.convert(this.price);
    }
    public void setPrice(com.beathive.model.Price price) throws Exception
    {
        setPriceForm((PriceForm) com.beathive.util.ConvertUtil.convert(price));
    }
    
    public boolean isSearchable()
    {
        return true;
    }
    public boolean isReady()
    {
        return true;
    }

    public String getScore()
    {
        return this.score;
    }
   /**
    */
    public void setScore( String score )
    {
        this.score = score;
    }
    
    /* To add non XDoclet-generated methods, create a file named
           xdoclet-LoopForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false
        this.ownedByViewer = false;
        this.aFavorite = false;
    	this.descriptors = new HashMap();
    }
	/**
	 * @return the descriptors
	 */
	public Map getDescriptors() {
		return descriptors;
	}
	/**
	 * @param descriptors the descriptors to set
	 */
	public void setDescriptors(Map descriptors) {
		this.descriptors = descriptors;
	}
    public void setDescriptors(String key, String value) {
    	if (StringUtils.isNotBlank(value)){
    		descriptors.put(key, value);
    	}
    }
    public void setDescriptor(String key, String value) {
    	if (StringUtils.isNotBlank(value)){
    		descriptors.put(key, value);
    	}
    }
	/**
	 * @return the values
	 */
	public String getDescriptors(String key) {
		return (String)descriptors.get(key);
	}

	/**
	 * @return the formatId
	 */
	public String getFormatId() {
		return formatId;
	}

	/**
	 * @param formatId the formatId to set
	 */
	public void setFormatId(String formatId) {
		this.formatId = formatId;
	}

	/**
	 * @return the genreId
	 */
	public String getGenreId() {
		return genreId;
	}

	/**
	 * @param genreId the genreId to set
	 */
	public void setGenreId(String genreId) {
		this.genreId = genreId;
	}

	/**
	 * @return the ownedByViewer
	 */
	public boolean isOwnedByViewer() {
		return ownedByViewer;
	}

	/**
	 * @param ownedByViewer the ownedByViewer to set
	 */
	public void setOwnedByViewer(boolean ownedByViewer) {
		this.ownedByViewer = ownedByViewer;
	}

	/**
	 * @return the trackpackId
	 */
	public String getTrackpackId() {
		return trackpackId;
	}

	/**
	 * @param trackpackId the trackpackId to set
	 */
	public void setTrackpackId(String trackpackId) {
		this.trackpackId = trackpackId;
	}

	/**
	 * @return the storeId
	 */
	public String getStoreId() {
		return storeId;
	}

	/**
	 * @param storeId the storeId to set
	 */
	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}

	/**
	 * @return the keyword
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * @param keyword the keyword to set
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	/**
	 * @return the energy
	 */
	public String getEnergy() {
		return energy;
	}

	/**
	 * @param energy the energy to set
	 */
	public void setEnergy(String energy) {
		this.energy = energy;
	}

	/**
	 * @return the feel
	 */
	public String getFeel() {
		return feel;
	}

	/**
	 * @param feel the feel to set
	 */
	public void setFeel(String feel) {
		this.feel = feel;
	}

	/**
	 * @return the keynote
	 */
	public String getKeynote() {
		return keynote;
	}

	/**
	 * @param keynote the keynote to set
	 */
	public void setKeynote(String keynote) {
		this.keynote = keynote;
	}

	/**
	 * @return the mood
	 */
	public String getMood() {
		return mood;
	}

	/**
	 * @param mood the mood to set
	 */
	public void setMood(String mood) {
		this.mood = mood;
	}

	/**
	 * @return the origin
	 */
	public String getOrigin() {
		return origin;
	}

	/**
	 * @param origin the origin to set
	 */
	public void setOrigin(String origin) {
		this.origin = origin;
	}

	/**
	 * @return the passage
	 */
	public String getPassage() {
		return passage;
	}

	/**
	 * @param passage the passage to set
	 */
	public void setPassage(String passage) {
		this.passage = passage;
	}

	/**
	 * @return the scale
	 */
	public String getScale() {
		return scale;
	}

	/**
	 * @param scale the scale to set
	 */
	public void setScale(String scale) {
		this.scale = scale;
	}

	/**
	 * @return the sonority
	 */
	public String getSonority() {
		return sonority;
	}

	/**
	 * @param sonority the sonority to set
	 */
	public void setSonority(String sonority) {
		this.sonority = sonority;
	}

	/**
	 * @return the texture
	 */
	public String getTexture() {
		return texture;
	}

	/**
	 * @param texture the texture to set
	 */
	public void setTexture(String texture) {
		this.texture = texture;
	}

	/**
	 * @return the timesignature
	 */
	public String getTimesignature() {
		return timesignature;
	}

	/**
	 * @param timesignature the timesignature to set
	 */
	public void setTimesignature(String timesignature) {
		this.timesignature = timesignature;
	}
	/**
	 * @return the timesignature
	 */
	public String getBpm() {
		return bpm;
	}
	
	/**
	 * @param bpm the bpm to set
	 */
	public void setBpm(String bpm) {
		this.bpm = bpm;
	}
	/**
	 * @return the timesignature
	 */
	public String getTempo() {
		return bpm;
	}
	
	/**
	 * @param bpm the bpm to set
	 */
	public void setTempo(String bpm) {
		this.bpm = bpm;
	}

	/**
	 * @return the sort
	 */
	public String getSort() {
		return sort;
	}

	/**
	 * @param sort the sort to set
	 */
	public void setSort(String sort) {
		this.sort = sort;
	}

	/**
	 * @return the dir
	 */
	public String getDir() {
		return dir;
	}

	/**
	 * @param dir the dir to set
	 */
	public void setDir(String dir) {
		this.dir = dir;
	}

	/**
	 * @return the preffrm
	 */
	public String getPreffrm() {
		return preffrm;
	}

	/**
	 * @param preffrm the preffrm to set
	 */
	public void setPreffrm(String preffrm) {
		this.preffrm = preffrm;
	}

	/**
	 * @return the size
	 */
	public String getSize() {
		return size;
	}

	/**
	 * @param size the size to set
	 */
	public void setSize(String size) {
		this.size = size;
	}
}
