package com.beathive.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="offenseForm" 
 */
public class OffenseForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String id;

    protected String companyName;

    protected String complaint;

    protected String description;

    protected String email;

    protected String fullname;

    protected String loopName;

    protected String producerName;

    protected String userip;

    protected String username;

    protected String creationTime;

    /** Default empty constructor. */
    public OffenseForm() {}

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getCompanyName()
    {
        return this.companyName;
    }
   /**
    */

    public void setCompanyName( String companyName )
    {
        this.companyName = companyName;
    }

    public String getComplaint()
    {
        return this.complaint;
    }
   /**
    */

    public void setComplaint( String complaint )
    {
        this.complaint = complaint;
    }

    public String getDescription()
    {
        return this.description;
    }
   /**
    */

    public void setDescription( String description )
    {
        this.description = description;
    }

    public String getEmail()
    {
        return this.email;
    }
   /**
    * @struts.validator type="required"
    * @struts.validator type="email"
    */

    public void setEmail( String email )
    {
        this.email = email;
    }

    public String getFullname()
    {
        return this.fullname;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFullname( String fullname )
    {
        this.fullname = fullname;
    }

    public String getLoopName()
    {
        return this.loopName;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLoopName( String loopName )
    {
        this.loopName = loopName;
    }

    public String getProducerName()
    {
        return this.producerName;
    }
   /**
    * @struts.validator type="required"
    */

    public void setProducerName( String producerName )
    {
        this.producerName = producerName;
    }

    public String getUserip()
    {
        return this.userip;
    }
   /**
    * @struts.validator type="required"
    */

    public void setUserip( String userip )
    {
        this.userip = userip;
    }

    public String getUsername()
    {
        return this.username;
    }
   /**
    */

    public void setUsername( String username )
    {
        this.username = username;
    }

    public String getCreationTime()
    {
        return this.creationTime;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCreationTime( String creationTime )
    {
        this.creationTime = creationTime;
    }

    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }
    
	public String toString(){
		String newLine="\n";
		StringBuffer buf = 
			new StringBuffer()
				.append("Producer Integrity Query")
				.append(newLine)
				.append("Complainant: ")
				.append(this.fullname);
		if (username!=null){
			buf
			.append(" (username: ")
			.append(this.username)
			.append(")");
		}
		buf
		.append(newLine)
		.append("From IP address: ")
		.append(this.userip)
		.append(newLine);
        if (companyName!=null){
        	buf
		.append("companyName : " + this.companyName)
		.append(newLine);
        }
        buf
		.append("email: " +  this.email)
		.append(newLine)
		.append("complaint: " +  this.complaint)
		.append(newLine)
		.append("loopName: " +  this.loopName)
		.append(newLine)
		.append("producerName: "+ this.producerName)
		.append(newLine)
		.append("description: ")
		.append(newLine)
		.append(this.description);
		return buf.toString();
	}

}
