package com.beathive.webapp.form;

import java.util.Iterator;


/**
 * RBD note: xdoclet template modified to skip User fields in POJO
 *
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="trackpackFormCart" 
 */
public class TrackpackFormCart extends TrackpackForm implements SoundClipFormCart , java.io.Serializable {

	private String fileId;
    public String type;

	public AudioFileForm getAudioFile(){
		AudioFileForm af = null;
		
		for ( Iterator it = super.getAudioFormat().iterator();
			  it.hasNext();
			  af = (AudioFileForm)it.next()
		) {
			if (af.getId().equals(this.fileId)){
				break;
			}
		}
		
		return af;
	}
	
	/**
	 * @return the formatId
	 */
	public String getFileId() {
		return fileId;
	}

	/**
	 * @param formatId the formatId to set
	 */
	public void setFileId(String ileId) {
		this.fileId = ileId;
	}
    
    public String getType() {
    	return this.type;
    }
    
    public void setType(String clazz) {
    	this.type = clazz;
    }
	
    public boolean equals(Object o ){
    	if (o != null && o instanceof TrackpackFormCart){
    		return this.id.equals(((TrackpackFormCart)o).getId());
    	}
    	return false; 
    }

    public int hashCode() {
        return new org.apache.commons.lang.builder.HashCodeBuilder()
        .append(this.id).toHashCode();
    }
    
    public String toString() {
    	return this.id +"_" + this.fileId;
    }
}

