package com.beathive.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.beathive.webapp.form.BaseForm;

/**
 * RBD note: xdoclet template modified to skip User fields in POJO
 *
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="userReportForm" 
 */
public class UserReportForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String firstName;

    protected String lastName;

    protected String username;

    protected String email;

    protected String middleName;

    protected boolean enabled;

    protected String modified;

    protected String startDate;

    protected String endDate;
    protected String roleName;

    /** Default empty constructor. */
    public UserReportForm() {}

    public String getFirstName()
    {
        return this.firstName;
    }
   /**
    */

    public void setFirstName( String firstName )
    {
        this.firstName = firstName;
    }

    public String getLastName()
    {
        return this.lastName;
    }
   /**
    */

    public void setLastName( String lastName )
    {
        this.lastName = lastName;
    }

    public String getUsername()
    {
        return this.username;
    }
   /**
    */

    public void setUsername( String username )
    {
        this.username = username;
    }

    public String getEmail()
    {
        return this.email;
    }
   /**
    */

    public void setEmail( String email )
    {
        this.email = email;
    }

    public String getMiddleName()
    {
        return this.middleName;
    }
   /**
    */

    public void setMiddleName( String middleName )
    {
        this.middleName = middleName;
    }

    public boolean isEnabled()
    {
        return this.enabled;
    }
   /**
    */

    public void setEnabled( boolean enabled )
    {
        this.enabled = enabled;
    }

    public String getModified()
    {
        return this.modified;
    }
   /**
    */

    public void setModified( String modified )
    {
        this.modified = modified;
    }

    public String getStartDate()
    {
        return this.startDate;
    }
   /**
    */

    public void setStartDate( String startDate )
    {
        this.startDate = startDate;
    }

    public String getEndDate()
    {
        return this.endDate;
    }
   /**
    */

    public void setEndDate( String endDate )
    {
        this.endDate = endDate;
    }

    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false
        this.enabled = false;
    }

	/**
	 * @return the roleId
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * @param roleId the roleId to set
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

}
